### ISSUE TITLE
Avez-vous remis une version en ligne ?

### ISSUE THREAD

**Issue by micbuffa** [rico237/projet_web-client_side#1]
Où est la version hébergée ? Merci d'avance ! Vous deviez corriger le déploiement ...

**Comment by rico237** [comment]
Normalement le déploiement est bien effectif sur le dépôt github. Je viens de mettre à jour le readme avec le lien du site déployé sur GitHub pages

Le lien :
https://rico237.github.io/projet_web-client_side/

**Comment by rico237** [comment]
La solution hébergé sur github pages est bien celle que nous vous avions présenté à l’oral (qui était à la base en local sur nos machines)

**Comment by micbuffa** [comment]
Bien reçu, merci !

Le ven. 1 mars 2019 à 13:26, Herrick Wolber <notifications@github.com> a
écrit :
